using MigraDoc.DocumentObjectModel;
using ReportingEngine.Core;
using ReportingEngine.Styles;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReportingEngine.Builders
{
    public class FooterBuilder
    {
        //public void Build(Section section)
        //{
        //    var p = section.Footers.Primary.AddParagraph();
        //    p.AddText("Generated by StaffSync");
        //    p.AddTab();
        //    p.AddPageField();
        //}

        public void Build()
        {
            // Footer rendering implementation.
        }
    }
}
